# Generated by Django 5.1.2 on 2025-01-26 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VKClip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('preview_url', models.URLField(null=True, verbose_name='URL превью')),
                ('post_url', models.URLField(verbose_name='URL поста')),
            ],
            options={
                'verbose_name': 'Клип',
                'verbose_name_plural': 'Клипы',
            },
        ),
    ]
