# Generated by Django 5.1.2 on 2025-01-29 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parsers', '0002_review2gis_alter_vkclip_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review2gis',
            options={'managed': False, 'verbose_name': 'Отзыв', 'verbose_name_plural': 'Отзывы'},
        ),
    ]
