# Generated by Django 5.1.2 on 2025-01-26 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parsers', '0002_review'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Review',
            new_name='Review2GIS',
        ),
    ]
