# Generated by Django 5.1.2 on 2025-01-26 16:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brands',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=250)),
                ('brand', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'brands',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=250)),
                ('year', models.IntegerField()),
                ('mileage', models.IntegerField()),
                ('price', models.IntegerField()),
                ('transmission', models.CharField(max_length=20)),
                ('engine_volume', models.IntegerField()),
                ('drive', models.CharField(max_length=20)),
                ('color', models.CharField(max_length=50)),
                ('power_volume', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'cars',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CarImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_type', models.CharField(choices=[('main', 'Main'), ('gallery', 'Gallery')], max_length=10)),
                ('image', models.ImageField(upload_to='')),
                ('order', models.IntegerField(blank=True, null=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.cars')),
            ],
            options={
                'db_table': 'car_img',
                'managed': True,
            },
        ),
    ]
