# Generated by Django 5.1.2 on 2025-01-26 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cars',
            options={'managed': True},
        ),
    ]
