# Generated by Django 5.1.2 on 2025-01-26 16:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_cars_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='cars',
            name='car_images',
            field=models.ManyToManyField(blank=True, related_name='cars', to='core.carimage'),
        ),
    ]
