# Generated by Django 5.1.2 on 2025-01-26 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_cars_brand_country_cars_car_images'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carimage',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='cars',
            options={'managed': False},
        ),
    ]
