# Generated by Django 5.1.2 on 2025-01-29 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_carimage_options_alter_cars_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('phone_number', models.CharField(max_length=16)),
                ('message', models.TextField(blank=True, max_length=200)),
                ('privacy_policy_confirm', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Пользовательская заявка',
                'verbose_name_plural': 'Пользовательские заявки',
                'db_table': 'feedbacks',
                'managed': True,
            },
        ),
        migrations.AlterModelOptions(
            name='brands',
            options={'managed': False, 'verbose_name': 'Бренд', 'verbose_name_plural': 'Бренды'},
        ),
        migrations.AlterModelOptions(
            name='carimage',
            options={'managed': False, 'verbose_name': 'Изображение авто', 'verbose_name_plural': 'Изображения авто'},
        ),
        migrations.AlterModelOptions(
            name='cars',
            options={'managed': False, 'verbose_name': 'Марка', 'verbose_name_plural': 'Марки авто'},
        ),
    ]
