# Generated by Django 5.1.2 on 2025-01-30 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_feedback_alter_brands_options_alter_carimage_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3, unique=True, verbose_name='Код валюты')),
                ('buy_rate', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Курс покупки валюты')),
                ('sell_rate', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Курс продажи валюты')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Время обновления')),
            ],
            options={
                'verbose_name': 'Валюта',
                'verbose_name_plural': 'Валюты',
                'db_table': 'currencies',
                'managed': True,
            },
        ),
        migrations.AlterModelOptions(
            name='feedback',
            options={'managed': False, 'verbose_name': 'Пользовательская заявка', 'verbose_name_plural': 'Пользовательские заявки'},
        ),
    ]
