# Generated by Django 5.1.2 on 2025-01-30 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_currency_alter_feedback_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='currency',
            options={'managed': False, 'verbose_name': 'Валюта', 'verbose_name_plural': 'Валюты'},
        ),
    ]
